from __future__ import annotations

import io
import os
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

from flask import Flask, jsonify, render_template, request, send_from_directory
from PIL import Image

import db
from ai.pipeline import process_image
from config import CAPTURES_DIR, HOST, MAX_UPLOAD_MB, PORT, PROCESSED_DIR, RECEIVED_DIR

app = Flask(__name__)
app.config["MAX_CONTENT_LENGTH"] = MAX_UPLOAD_MB * 1024 * 1024


@app.after_request
def add_cors_headers(response):
    response.headers["Access-Control-Allow-Origin"] = "*"
    response.headers["Access-Control-Allow-Methods"] = "GET, POST, OPTIONS"
    response.headers["Access-Control-Allow-Headers"] = "*"
    return response

db.init_db()
executor = ThreadPoolExecutor(max_workers=2)


def safe_filename(filename: str) -> str:
    # Upload names are generated by the server; this also protects manual endpoints.
    clean = Path(filename or "").name.replace("..", "_")
    clean = clean.replace("\\", "/")
    return clean.split("/")[-1]


def process_frame_id(frame_id: int):
    frame = db.get_frame(frame_id)
    if not frame:
        raise ValueError("Frame not found")
    path = RECEIVED_DIR / safe_filename(frame["filename"])
    if not path.exists():
        raise FileNotFoundError(f"Missing capture file: {path.name}")
    result = process_image(path)
    db.update_processing(frame_id, result=result)
    return result


@app.get("/")
def home():
    return render_template("index.html")


@app.get("/health")
def health():
    from config import TESSERACT_AVAILABLE, TESSERACT_VERSION, ENABLE_OLLAMA
    frames = db.list_frames(1000)
    accepted = sum(1 for frame in frames if frame.get("processing_status") == "complete")
    rejected = sum(1 for frame in frames if frame.get("processing_status") in {"failed", "no_text", "low_confidence", "missing_tesseract"})
    return jsonify({
        "ok": True,
        "service": "EdgeBoard AI",
        "port": PORT,
        "tesseract_available": TESSERACT_AVAILABLE,
        "tesseract_version": TESSERACT_VERSION or "unavailable",
        "ollama_enabled": ENABLE_OLLAMA,
        "capture_count": len(frames),
        "accepted_count": accepted,
        "rejected_count": rejected,
    })


@app.get("/status")
def status():
    return health()


@app.get("/api/latest")
def api_latest():
    frames = db.list_frames(1)
    return jsonify(frames[0] if frames else None)


@app.get("/api/frames")
def api_frames():
    try:
        limit = max(1, min(100, int(request.args.get("limit", 50))))
    except ValueError:
        limit = 50
    return jsonify(db.list_frames(limit))


@app.get("/api/frames/<int:frame_id>")
def api_frame(frame_id):
    frame = db.get_frame(frame_id)
    if not frame:
        return jsonify({"error": "Frame not found"}), 404
    return jsonify(frame)


@app.post("/api/process/<int:frame_id>")
def api_process(frame_id):
    try:
        result = process_frame_id(frame_id)
        return jsonify({"success": True, "result": result})
    except Exception as exc:
        db.update_processing(frame_id, error=str(exc))
        return jsonify({"success": False, "error": str(exc)}), 500


@app.get("/captures/<path:filename>")
def captured_file(filename):
    safe_name = safe_filename(filename)
    safe_path = (RECEIVED_DIR / safe_name).resolve()
    if not safe_path.exists() or not safe_path.is_file() or safe_path.parent.resolve() != RECEIVED_DIR.resolve():
        return jsonify({"error": "Capture not found"}), 404
    return send_from_directory(RECEIVED_DIR, safe_name)


@app.get("/processed/<path:filename>")
def processed_file(filename):
    safe_name = safe_filename(filename)
    safe_path = (PROCESSED_DIR / safe_name).resolve()
    if not safe_path.exists() or not safe_path.is_file() or safe_path.parent.resolve() != PROCESSED_DIR.resolve():
        return jsonify({"error": "Processed file not found"}), 404
    return send_from_directory(PROCESSED_DIR, safe_name)


def _background_process(frame_id: int):
    try:
        process_frame_id(frame_id)
    except Exception as exc:
        db.update_processing(frame_id, error=f"Image processing failed: {exc}")
        print(f"[PROCESSING ERROR] frame={frame_id}: {exc}")


@app.get("/snapshot")
def snapshot():
    latest = db.list_frames(1)
    if not latest:
        return jsonify({"error": "No frame available"}), 404
    return send_from_directory(RECEIVED_DIR, safe_filename(latest[0]["filename"]))


@app.post("/upload")
def upload():
    data = request.get_data()
    if not data:
        return jsonify({"success": False, "message": "No image received"}), 400
    if len(data) > MAX_UPLOAD_MB * 1024 * 1024:
        return jsonify({"success": False, "message": "Image too large"}), 413

    try:
        with Image.open(io.BytesIO(data)) as img:
            img.verify()
        with Image.open(io.BytesIO(data)) as img:
            img.load()
            if img.format != "JPEG":
                raise ValueError("Uploaded file is not a JPEG image")
    except Exception as exc:
        return jsonify({"success": False, "message": f"Invalid or unreadable JPEG: {exc}"}), 400

    from datetime import datetime, timezone
    filename = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S_%f") + ".jpg"
    path = RECEIVED_DIR / filename
    path.write_bytes(data)

    frame_id = db.insert_frame(filename, len(data), request.headers)
    executor.submit(_background_process, frame_id)

    return jsonify({
        "success": True,
        "status": "accepted",
        "filename": filename,
        "frame_id": frame_id,
        "processing_error": "",
    }), 202


@app.get("/frames")
def frames_alias():
    return api_frames()


@app.get("/frames/<int:frame_id>")
def frame_alias(frame_id):
    return api_frame(frame_id)


@app.post("/reprocess")
def reprocess_alias():
    frame_id = request.form.get("id") or request.get_json(silent=True, force=False) or {}
    if isinstance(frame_id, dict):
        frame_id = frame_id.get("id")
    try:
        frame_id = int(frame_id)
    except (TypeError, ValueError):
        return jsonify({"success": False, "error": "Missing or invalid frame id"}), 400
    try:
        result = process_frame_id(frame_id)
        return jsonify({"success": True, "result": result})
    except Exception as exc:
        db.update_processing(frame_id, error=str(exc))
        return jsonify({"success": False, "error": str(exc)}), 500


@app.post("/api/reprocess-all")
def reprocess_all():
    frames = db.list_frames(1000)
    completed = failed = 0
    for frame in frames:
        try:
            process_frame_id(frame["id"])
            completed += 1
        except Exception as exc:
            db.update_processing(frame["id"], error=str(exc))
            failed += 1
    return jsonify({"success": True, "completed": completed, "failed": failed})


if __name__ == "__main__":
    print("=" * 56)
    print("EDGEBOARD AI — local laptop server")
    print(f"Dashboard : http://127.0.0.1:{PORT}")
    print(f"Network   : http://<LAPTOP-IP>:{PORT}")
    print("Upload    : POST /upload")
    print("=" * 56)
    app.run(host=HOST, port=PORT, debug=False, threaded=True)
